AWSTemplateFormatVersion: 2010-09-09
Description: |
    Kittens Carousel is a static website application deployed on AWS Simple Storage Service (S3), served through Cloudfront and Route 53 using AWS Cloudformation Service.

  
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: kitten.clarusway.us
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

      Tags: 
        - Key: Name
          Value: kitten-static-website-bucket
      WebsiteConfiguration:
        IndexDocument: index.html
        
  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref MyS3Bucket
                - /*
            Principal: '*'
            Sid: PublicReadGetObject


  MyCloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref MyS3Bucket
        DefaultCacheBehavior:
          AllowedMethods: 
            - GET
            - HEAD
          ForwardedValues: 
              Cookies: 
                Forward: none
              QueryString: true
          TargetOriginId: KittensOrigin
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
          - CustomOriginConfig: 
              OriginProtocolPolicy: http-only
            DomainName: kitten.clarusway.us.s3-website.us-east-1.amazonaws.com
            Id: KittensOrigin
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:046402772087:certificate/817294e2-3c97-4f76-9c8d-dd59b2587904
          SslSupportMethod: sni-only

  MyDNSRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: Z08348542LMKDSH94CCW6
      RecordSets: 
        - AliasTarget: 
            DNSName: !GetAtt MyCloudfrontDistribution.DomainName
            HostedZoneId: Z08348542LMKDSH94CCW6
          Name: !Ref MyS3Bucket
          Type: A


Outputs:
  MyBucketWebsiteURL:
    Description: The URL of the static webpage.
    Value: !GetAtt MyS3Bucket.WebsiteURL

  FullyQualifiedDomainName:
    Description: FQDN
    Value: !Ref MyS3Bucket